# Generated by Django 5.2.15 on 2026-09-15 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_orders', '0005_customrequest_budget_range_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConceptGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('text_prompt', 'Text Description'), ('reference_image', 'Uploaded Photo')], default='text_prompt', max_length=20)),
                ('input_text', models.TextField(blank=True)),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='ai_concepts/inputs/')),
                ('generated_images', models.JSONField(default=list)),
                ('selected_concept_index', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_concepts', to=settings.AUTH_USER_MODEL)),
                ('linked_custom_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_concept_sources', to='custom_orders.customrequest')),
            ],
        ),
    ]
