# Generated by Django 5.2.15 on 2026-09-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('excerpt', models.TextField()),
                ('content', models.JSONField(default=list, help_text='List of paragraphs or text blocks')),
                ('read_time', models.CharField(default='5 min read', max_length=30)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('author_name', models.CharField(default='Harshil Shah', max_length=100)),
                ('author_role', models.CharField(default='Head CAD Engineer', max_length=100)),
                ('author_avatar', models.ImageField(blank=True, null=True, upload_to='blog/authors/')),
                ('author_avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/')),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, to='blog.blogtag')),
            ],
            options={
                'ordering': ['-date_published', '-created_at'],
            },
        ),
    ]
