# Generated by Django 5.2.15 on 2026-09-15 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_orders', '0005_customrequest_budget_range_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FileEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('original_file', models.FileField(upload_to='file_edits/originals/')),
                ('original_file_format', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='file_edits/references/')),
                ('status', models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('negotiating', 'Negotiating'), ('agreed', 'Agreed'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('submission_intent', models.CharField(choices=[('quote_only', 'Request a Quote'), ('place_order', 'Submit Modification Order')], default='quote_only', max_length=20)),
                ('estimated_price_shown', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_edit_requests', to=settings.AUTH_USER_MODEL)),
                ('converted_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_edit_source', to='custom_orders.order')),
                ('modification_types', models.ManyToManyField(related_name='edit_requests', to='file_edits.modificationtype')),
            ],
        ),
    ]
