# Generated by Django 5.2.15 on 2026-09-15 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_atelier_license_desc_and_more'),
        ('custom_orders', '0005_customrequest_budget_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category_slug', models.CharField(blank=True, max_length=100)),
                ('is_ai_project', models.BooleanField(default=False)),
                ('is_custom_project', models.BooleanField(default=False)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='portfolio/primary/')),
                ('description', models.TextField(blank=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
                ('gallery_images', models.ManyToManyField(blank=True, to='portfolio.portfolioimage')),
                ('source_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_orders.order')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
