# Generated by Django 5.2.15 on 2026-09-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='primary_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='sketch_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/sketches/'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='sketch_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='specs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
