# Generated by Django 5.2.15 on 2026-09-14 08:03

import apps.catalog.models
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='atelier_license_desc',
            field=models.TextField(default='Workshop & bespoke client casts', help_text='Short description of Atelier License'),
        ),
        migrations.AddField(
            model_name='product',
            name='commercial_license_desc',
            field=models.TextField(default='Global factory manufacturing & mass production', help_text='Short description of Commercial Mass License'),
        ),
        migrations.AddField(
            model_name='product',
            name='commercial_price_markup',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Percentage markup for Commercial Mass license (e.g. 80.00 for +80%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/Harshil/OneDrive/Desktop/shiuli-cad-studio/backend/protected_media')), upload_to=apps.catalog.models.product_file_upload_to),
        ),
    ]
