# Generated by Django 5.2.15 on 2026-09-23 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productimage_image_url_alter_productimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Studio commission percentage for this category (e.g. 20.00 for 20%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='agreed_terms',
            field=models.BooleanField(default=False, help_text='Staff agreed to commission and watertight CAD terms'),
        ),
        migrations.AddField(
            model_name='product',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated studio commission in currency', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Category commission rate percentage applied at listing', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this product is active and visible in catalog'),
        ),
        migrations.AddField(
            model_name='product',
            name='staff_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Staff asking price or net payout', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['staff', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
