# Generated by Django 5.2.15 on 2026-09-29 12:10

import apps.catalog.models
import django.core.files.storage
import django.utils.timezone
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_commission_percentage_product_agreed_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='file_size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productfile',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='productfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media/', location=pathlib.PureWindowsPath('C:/Users/HP/Desktop/Shiuli/backend/protected_media')), upload_to=apps.catalog.models.product_file_upload_to),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file_type',
            field=models.CharField(choices=[('3dm', '3DM (Rhino)'), ('stl', 'STL'), ('render', 'Render Image'), ('video', '360 Video'), ('zip', 'ZIP Archive (all CAD files)')], max_length=10),
        ),
    ]
