# Generated by Django 5.2.15 on 2026-09-30 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_zip_type_and_file_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
