# Generated by Django 5.2.15 on 2026-09-22 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountotp',
            name='otp_type',
            field=models.CharField(choices=[('email_change', 'Email Change'), ('password_reset', 'Password Reset'), ('registration', 'Registration')], max_length=20),
        ),
        migrations.AlterField(
            model_name='accountotp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
