# Generated by Django 5.1.15 on 2026-09-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_max_job_limit', models.PositiveIntegerField(default=2)),
                ('assignment_mode', models.CharField(choices=[('first_accept_wins', 'First Accept Wins'), ('priority_least_loaded', 'Priority (Least Loaded First)')], default='first_accept_wins', max_length=30)),
                ('auto_escalation_minutes', models.PositiveIntegerField(default=30)),
                ('advance_payment_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
