# Generated by Django 5.2.15 on 2026-09-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='studio_name',
            field=models.CharField(default='Shiuli CAD Studio', max_length=100),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='timezone',
            field=models.CharField(default='IST (UTC+5:30)', max_length=50),
        ),
    ]
