# Generated by Django 5.2.15 on 2026-09-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0002_platformsettings_studio_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='cash_check_instructions',
            field=models.TextField(blank=True, default='For Cash or Cheque, please submit your transaction details and attach deposit receipt or cheque photo. Atelier accounts will confirm collection and enable your download.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='studio_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='settings/qr/'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='studio_qr_code_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='studio_upi_id',
            field=models.CharField(blank=True, default='shiulicad@okhdfcbank', max_length=100),
        ),
    ]
