# Generated by Django 5.2.15 on 2026-09-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0003_platformsettings_cash_check_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='extra_revision_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='free_revisions_allowed',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
