# Generated by Django 5.2.15 on 2026-09-11 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0003_alter_order_status'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('advance', 'Advance'), ('balance', 'Balance'), ('stage', 'Milestone Stage Payment'), ('full', 'Full Payment')], default='stage', max_length=10),
        ),
        migrations.CreateModel(
            name='OrderPaymentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_index', models.PositiveIntegerField()),
                ('trigger_type', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('due', 'Due Now'), ('paid', 'Paid')], default='locked', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_stages', to='custom_orders.order')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.orderpaymentstage'),
        ),
        migrations.CreateModel(
            name='PaymentPlanTemplateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_index', models.PositiveIntegerField()),
                ('trigger_type', models.CharField(choices=[('immediate', 'Due Immediately'), ('on_design_approval', 'Due on Client Design Approval'), ('on_final_delivery', 'Due Before Final File Release')], default='immediate', max_length=30)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='payments.paymentplantemplate')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
    ]
