# Generated by Django 5.2.15 on 2026-09-14 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_atelier_license_desc_and_more'),
        ('payments', '0002_paymentplantemplate_alter_payment_payment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('atelier', 'Atelier License'), ('commercial', 'Commercial Mass License')], default='atelier', max_length=20)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_transaction_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('redelivery_count', models.PositiveIntegerField(default=0)),
                ('otp_generation_count', models.PositiveIntegerField(default=0)),
                ('last_otp_generated_at', models.DateTimeField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('locked_email', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='payments.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='payments.purchase')),
            ],
        ),
    ]
