# Generated by Django 5.2.15 on 2026-09-14 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0004_order_admin_review_notes_order_deadline_hours_and_more'),
        ('payments', '0003_purchase_downloadtoken_downloadotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadotp',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='custom_orders.order'),
        ),
        migrations.AddField(
            model_name='downloadtoken',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='custom_orders.order'),
        ),
        migrations.AlterField(
            model_name='downloadotp',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='payments.purchase'),
        ),
        migrations.AlterField(
            model_name='downloadtoken',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='payments.purchase'),
        ),
    ]
