# Generated by Django 5.2.15 on 2026-09-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_downloadotp_order_downloadtoken_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='settlement',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payment_method',
            field=models.CharField(blank=True, default='bank_transfer', max_length=50),
        ),
        migrations.AddField(
            model_name='settlement',
            name='transaction_ref',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Settled'), ('processed', 'Processed')], default='pending', max_length=15),
        ),
    ]
