# Generated by Django 5.1.15 on 2026-09-09 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('custom_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AestheticStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_addon', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GemstoneOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_type', models.CharField(max_length=50)),
                ('cut_type', models.CharField(max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MetalAlloy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('swatch_color', models.CharField(default='#D4AF37', max_length=7)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='customrequest',
            name='estimated_price_shown',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='gemstone_preference_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='timeline',
            field=models.CharField(default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='customrequest',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_requests/references/'),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='aesthetic_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_orders.aestheticstyle'),
        ),
        migrations.CreateModel(
            name='CustomRequestGemstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_type', models.CharField(max_length=50)),
                ('cut_type', models.CharField(max_length=50)),
                ('carat_size', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemstones', to='custom_orders.customrequest')),
            ],
        ),
        migrations.CreateModel(
            name='CustomRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='custom_requests/sketches/')),
                ('is_draft', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sketches', to='custom_orders.customrequest')),
            ],
        ),
        migrations.AddField(
            model_name='customrequest',
            name='metal_alloy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_orders.metalalloy'),
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, default=75.0, max_digits=10)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rule', to='catalog.category')),
            ],
        ),
    ]
