# Generated by Django 5.2.15 on 2026-09-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0002_aestheticstyle_gemstoneoption_metalalloy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Booking Payment'), ('in_design', 'In Design (In Pool)'), ('with_designer', 'With CAD Designer'), ('pending_final_payment', 'Pending Final Payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='awaiting_payment', max_length=30),
        ),
    ]
