# Generated by Django 5.2.15 on 2026-09-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deadline_hours',
            field=models.PositiveIntegerField(default=72),
        ),
        migrations.AddField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_orders/previews/'),
        ),
        migrations.AddField(
            model_name='order',
            name='quality_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='warning_50_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='warning_80_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Booking Payment'), ('in_design', 'In Pool (Awaiting Designer)'), ('with_designer', 'With CAD Designer'), ('pending_review', 'Pending Admin Quality Review'), ('preview_ready', 'Design Preview Ready for Client'), ('pending_final_payment', 'Pending Final Payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='awaiting_payment', max_length=30),
        ),
    ]
