# Generated by Django 5.2.15 on 2026-09-15 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_atelier_license_desc_and_more'),
        ('custom_orders', '0004_order_admin_review_notes_order_deadline_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequest',
            name='budget_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='engraving_font',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='engraving_placement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='engraving_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='has_logo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='is_metal_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='logo_file',
            field=models.FileField(blank=True, null=True, upload_to='custom_requests/logos/'),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='needed_by_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='ring_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='ring_size_standard',
            field=models.CharField(blank=True, choices=[('us', 'US'), ('uk', 'UK'), ('eu', 'EU'), ('in', 'Indian'), ('mm', 'Diameter mm')], max_length=10),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='submission_intent',
            field=models.CharField(choices=[('quote_only', 'Request a Quote'), ('place_order', 'Submit Custom Order')], default='quote_only', max_length=20),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='target_weight_grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='customrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CustomRequestStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_type', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size_value', models.CharField(blank=True, max_length=50)),
                ('size_unit', models.CharField(choices=[('carat', 'Carat'), ('mm', 'mm'), ('sieve', 'Sieve')], default='carat', max_length=10)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('clarity', models.CharField(blank=True, max_length=50)),
                ('is_center_stone', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stones', to='custom_orders.customrequest')),
            ],
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('allows_other', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('applies_to_categories', models.ManyToManyField(blank=True, to='catalog.category')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modifier_type', models.CharField(choices=[('flat', 'Flat Add-on'), ('percent', 'Percentage Multiplier')], default='flat', max_length=10)),
                ('swatch_color', models.CharField(blank=True, max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='custom_orders.optiongroup')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomRequestSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_text', models.CharField(blank=True, max_length=200)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='custom_orders.customrequest')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom_orders.optiongroup')),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom_orders.optionvalue')),
            ],
        ),
        migrations.AddField(
            model_name='customrequest',
            name='delivery_speed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_requests', to='custom_orders.optionvalue'),
        ),
    ]
