# Generated by Django 5.2.15 on 2026-09-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0006_customrequest_client_consent_to_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrequest',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customrequest',
            name='ring_size_standard',
            field=models.CharField(blank=True, choices=[('us', 'US'), ('uk', 'UK'), ('eu', 'EU'), ('in', 'Indian'), ('in_hk', 'Indian / HK'), ('mm', 'Diameter mm')], max_length=10),
        ),
    ]
