# Generated by Django 5.2.15 on 2026-09-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0007_alter_customrequest_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customrequeststone',
            name='setting_style',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customrequeststone',
            name='shape',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
