# Generated by Django 5.2.15 on 2026-09-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0008_customrequest_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='download_enabled_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='download_otp',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='download_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='download_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='download_token_used',
            field=models.BooleanField(default=False),
        ),
    ]
