# Generated by Django 5.2.15 on 2026-09-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0009_order_download_count_order_download_enabled_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequest',
            name='catalog_references_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
