# Generated by Django 5.2.15 on 2026-09-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productimage_image_url_alter_productimage_image'),
        ('custom_orders', '0010_customrequest_catalog_references_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequest',
            name='reference_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_custom_requests', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='request_mode',
            field=models.CharField(choices=[('step_by_step', 'Step by Step'), ('quick', 'Quick Request')], default='step_by_step', max_length=20),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='voice_recording',
            field=models.FileField(blank=True, null=True, upload_to='custom_requests/voice_notes/'),
        ),
    ]
