# Generated by Django 5.2.15 on 2026-09-24 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0011_customrequest_reference_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderdeliverable',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Booking Payment'), ('in_design', 'In Pool (Awaiting Designer)'), ('with_designer', 'With CAD Designer'), ('pending_review', 'Pending Admin Quality Review'), ('preview_ready', 'Design Preview Ready for Client'), ('revision_requested', 'Changes Requested — Studio Reviewing'), ('pending_final_payment', 'Pending Final Payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='awaiting_payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordermilestone',
            name='stage',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_version', models.PositiveIntegerField(default=1)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('comment', models.TextField()),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='orders/revisions/voice/')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='orders/revisions/images/')),
                ('is_paid', models.BooleanField(default=True)),
                ('fee_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('addressed', 'Addressed'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addressed_at', models.DateTimeField(blank=True, null=True)),
                ('addressed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressed_revisions', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='custom_orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
