# Generated by Django 5.2.15 on 2026-09-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0012_order_current_version_orderdeliverable_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequest',
            name='admin_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='staff_payout_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
