# Generated by Django 5.2.15 on 2026-09-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0013_customrequest_admin_commission_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequest',
            name='admin_call_notes',
            field=models.TextField(blank=True, default='', help_text='Admin consultation, call discussion notes, and private order information'),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_call_notes',
            field=models.TextField(blank=True, default='', help_text='Admin consultation, call discussion notes, and private order information'),
        ),
    ]
